"""Generator agent: converts a Flow's steps into an executable
pytest-playwright test file.

TODO (team, live at the event):
  - For every `FlowStep.target_description`, query the *live* page (navigate
    with Playwright, then use role/label/text-based locators) for a
    resolvable selector — prefer semantic locators over brittle CSS/XPath.
  - If a description doesn't resolve to exactly one element, retry with
    feedback (e.g. re-prompt an LLM call with the surrounding DOM/ARIA
    subtree) before giving up on that step.
  - Only set `validation_status="validated"` once every step's selector is
    confirmed to resolve on the live page; otherwise leave "unresolved".
  - Replace the placeholder test body below with one that actually performs
    each `FlowStep.action` against its resolved selector and checks
    `expected_outcome`.
"""
from __future__ import annotations

import logging
from pathlib import Path

from orchestrator.schemas import Flow, GeneratedTest

logger = logging.getLogger(__name__)

GENERATED_TESTS_DIR = Path(__file__).resolve().parents[1] / "generated_tests"


class Generator:
    def generate(self, flow: Flow) -> GeneratedTest:
        """Trivial pass-through: writes a test file that navigates to the
        flow's first `navigate` step (if any) and asserts the page loaded.
        Every step's selector is a naive text-selector guess, never checked
        against a live page, so `validation_status` is always "unresolved".
        See TODO above.
        """
        GENERATED_TESTS_DIR.mkdir(parents=True, exist_ok=True)
        file_path = GENERATED_TESTS_DIR / f"test_{flow.flow_id}.py"

        selector_map = {step.step_id: f"text={step.target_description!r}" for step in flow.steps}
        first_navigate = next((s for s in flow.steps if s.action == "navigate" and s.value), None)

        self._write_test_file(file_path, flow, first_navigate.value if first_navigate else None)
        logger.info("Generator: wrote %s for flow %s (validation_status=unresolved)", file_path, flow.flow_id)

        return GeneratedTest(
            flow_id=flow.flow_id,
            file_path=str(file_path),
            selector_map=selector_map,
            validation_status="unresolved",
        )

    @staticmethod
    def _write_test_file(file_path: Path, flow: Flow, target_url: str | None) -> None:
        header = [
            '"""Auto-generated by Generator (placeholder logic — see agents/generator.py TODO)."""',
            "import pytest",
            "",
            f"def test_{flow.flow_id.replace('-', '_')}(page):",
            f"    # Flow: {flow.title} (category={flow.category}, priority={flow.priority})",
        ]
        step_comments = [
            f"    # TODO step {step.step_id}: {step.action} -> {step.target_description!r}" for step in flow.steps
        ]
        if target_url:
            body = [
                f"    page.goto({target_url!r})",
                "    assert page.title() is not None  # TODO: replace with resolved per-step assertions",
            ]
        else:
            body = ["    pytest.skip('TODO: no navigable target_description resolved for this flow yet')"]

        content = "\n".join(header + step_comments + body) + "\n"
        file_path.write_text(content, encoding="utf-8")
