"""Generator agent: converts a Flow's steps into an executable
pytest-playwright test file, resolving each step's `target_description`
against the *live* application (not guessed selectors).

Auth contract (coordinated with Executor — see its module docstring):
  - An `auth_session` flow's login `fill` steps carry the literal
    placeholders `{{username}}` / `{{password}}` as `FlowStep.value` (set by
    the Planner, which never sees real credentials). This Generator
    substitutes real values *only in memory*, for its own live resolution
    pass — the generated `.py` file never contains a plaintext secret. It
    instead reads `os.environ["ORCH_TEST_USERNAME"/"ORCH_TEST_PASSWORD"]` at
    run time; Executor sets those two env vars from the credentials file
    when it invokes pytest.
  - After successfully resolving an `auth_session` flow live, this Generator
    persists `context.storage_state()` to `STORAGE_STATE_PATH` and writes a
    `conftest.py` into `generated_tests/` that overrides the
    `browser_context_args` fixture to load it — but only when the
    `ORCH_STORAGE_STATE_PATH` env var is set for that pytest run. Executor
    sets that env var for every flow *except* the auth_session flow itself
    (which must start logged out to actually test login), so every other
    generated test starts pre-authenticated instead of re-running login.

TODO (team, live at the event):
  - If a description doesn't resolve to exactly one element, this currently
    just gives up on that step (and every step after it, since we no longer
    trust the page state). Consider retrying with feedback — e.g. re-prompt
    an LLM call with the surrounding DOM/ARIA subtree — before giving up.
  - Locator strategies below are a fixed heuristic list (label -> placeholder
    -> role -> text). Consider ranking by confidence instead of first-match.
  - One fresh browser per flow is simple/isolated but adds latency; consider
    reusing a single browser across a `generate()` batch if that matters.
"""
from __future__ import annotations

import logging
from pathlib import Path

from playwright.sync_api import Error as PlaywrightError
from playwright.sync_api import Locator, Page, TimeoutError as PlaywrightTimeoutError
from playwright.sync_api import sync_playwright

from orchestrator.schemas import Flow, FlowStep, GeneratedTest

logger = logging.getLogger(__name__)

GENERATED_TESTS_DIR = Path(__file__).resolve().parents[1] / "generated_tests"
STORAGE_STATE_PATH = GENERATED_TESTS_DIR / ".auth" / "state.json"
DIAGNOSTICS_DIR = GENERATED_TESTS_DIR / ".diagnostics"

_PLACEHOLDER_ENV_VARS = {
    "{{username}}": "ORCH_TEST_USERNAME",
    "{{password}}": "ORCH_TEST_PASSWORD",
}

_LOCATOR_STRATEGIES_BY_ACTION: dict[str, list[str]] = {
    "fill": ["label", "placeholder", "role_textbox", "input_type_heuristic"],
    "select": ["label", "role_combobox"],
    "click": ["role_button", "role_link", "text"],
    "assert_visible": ["text", "label", "role_button", "role_link"],
    "assert_text": ["text", "label"],
}

_CONFTEST_CONTENT = '''"""Auto-generated by Generator. Two things Executor coordinates through this
file, per pytest subprocess run (one generated test = one subprocess):
  - ORCH_STORAGE_STATE_PATH: injects a captured login session into every
    generated test except the auth_session flow's own test.
  - ORCH_DIAGNOSTICS_PATH: where this run's console errors and network
    errors (4xx/5xx responses, failed requests, and requests still pending
    when the test ends — e.g. a backend call that never responds) are
    written as JSON for Executor to read back into ExecutionResult.
"""
import json
import os

import pytest


@pytest.fixture(scope="session")
def browser_context_args(browser_context_args):
    storage_state_path = os.environ.get("ORCH_STORAGE_STATE_PATH")
    if storage_state_path and os.path.exists(storage_state_path):
        return {**browser_context_args, "storage_state": storage_state_path}
    return browser_context_args


@pytest.fixture(autouse=True)
def _orch_capture_diagnostics(page):
    console_errors = []
    network_errors = []
    pending_requests = {}

    def on_console(msg):
        if msg.type == "error":
            console_errors.append(msg.text)

    def on_request(request):
        pending_requests[request] = request

    def on_requestfinished(request):
        pending_requests.pop(request, None)

    def on_response(response):
        if response.status >= 400:
            network_errors.append(f"{response.status} {response.request.method} {response.url}")

    def on_requestfailed(request):
        pending_requests.pop(request, None)
        network_errors.append(f"FAILED {request.method} {request.url}: {request.failure}")

    page.on("console", on_console)
    page.on("request", on_request)
    page.on("requestfinished", on_requestfinished)
    page.on("response", on_response)
    page.on("requestfailed", on_requestfailed)

    yield

    for request in pending_requests:
        network_errors.append(f"NO RESPONSE (still pending when the test ended) {request.method} {request.url}")

    diagnostics_path = os.environ.get("ORCH_DIAGNOSTICS_PATH")
    if diagnostics_path:
        os.makedirs(os.path.dirname(diagnostics_path), exist_ok=True)
        with open(diagnostics_path, "w", encoding="utf-8") as f:
            json.dump({"console_errors": console_errors, "network_errors": network_errors}, f)
'''


class Generator:
    def generate(self, flow: Flow, credentials: dict | None = None) -> GeneratedTest:
        GENERATED_TESTS_DIR.mkdir(parents=True, exist_ok=True)
        _ensure_conftest()
        file_path = GENERATED_TESTS_DIR / f"test_{flow.flow_id}.py"

        try:
            resolved_lines, selector_map, all_resolved = self._resolve_live(flow, credentials)
        except Exception as exc:  # noqa: BLE001 - live resolution must never crash the pipeline
            logger.warning(
                "Generator: live resolution errored for flow %s (%s); falling back to a smoke test",
                flow.flow_id, exc,
            )
            resolved_lines, selector_map, all_resolved = None, {}, False

        if resolved_lines is None:
            selector_map = {step.step_id: f"text={step.target_description!r}" for step in flow.steps}
            first_navigate = next((s for s in flow.steps if s.action == "navigate" and s.value), None)
            _write_fallback_test_file(file_path, flow, first_navigate.value if first_navigate else None)
            status = "unresolved"
        else:
            _write_resolved_test_file(file_path, flow, resolved_lines)
            status = "validated" if all_resolved else "unresolved"

        logger.info("Generator: wrote %s for flow %s (validation_status=%s)", file_path, flow.flow_id, status)
        return GeneratedTest(
            flow_id=flow.flow_id, file_path=str(file_path), selector_map=selector_map, validation_status=status
        )

    def _resolve_live(
        self, flow: Flow, credentials: dict | None
    ) -> tuple[list[str], dict[str, str], bool]:
        is_auth_flow = flow.category == "auth_session"
        is_destructive_flow = flow.category == "destructive_action"
        storage_state = str(STORAGE_STATE_PATH) if (not is_auth_flow and STORAGE_STATE_PATH.exists()) else None

        resolved_lines: list[str] = []
        selector_map: dict[str, str] = {}
        all_resolved = True
        stopped_early = False

        with sync_playwright() as pw:
            browser = pw.chromium.launch(headless=True)
            context = browser.new_context(storage_state=storage_state) if storage_state else browser.new_context()
            page = context.new_page()

            for step in flow.steps:
                if stopped_early:
                    resolved_lines.append(
                        f"    # UNRESOLVED step {step.step_id}: {step.action} -> "
                        f"{step.target_description!r} (skipped after an earlier step failed to resolve)"
                    )
                    all_resolved = False
                    continue

                try:
                    line, selector_expr = self._resolve_step(page, step, credentials, is_destructive_flow)
                except (PlaywrightError, PlaywrightTimeoutError) as exc:
                    logger.info("Generator: step %s failed to resolve live: %s", step.step_id, exc)
                    line, selector_expr = None, None

                if line is None:
                    resolved_lines.append(
                        f"    # UNRESOLVED step {step.step_id}: {step.action} -> {step.target_description!r}"
                    )
                    all_resolved = False
                    stopped_early = True
                    continue

                resolved_lines.append(line)
                if selector_expr:
                    selector_map[step.step_id] = selector_expr

                # Capture after every successfully resolved step (not just once
                # at the end): the actual login (navigate/fill/fill/click)
                # usually resolves fine even when a later, purely cosmetic
                # assertion (e.g. "flash message") doesn't — a failure there
                # shouldn't throw away an otherwise-valid authenticated session.
                if is_auth_flow:
                    STORAGE_STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
                    context.storage_state(path=str(STORAGE_STATE_PATH))

            if is_auth_flow:
                logger.info(
                    "Generator: captured storage_state after auth_session flow %s "
                    "(fully_resolved=%s, final_url=%s)",
                    flow.flow_id, not stopped_early, page.url,
                )

            context.close()
            browser.close()

        # A function body made only of `# UNRESOLVED ...` comments (every step
        # failed) has no actual statement, which is a Python syntax error, not
        # a meaningful test failure — pad it with `pass` so it's collectible.
        has_statement = any(not line.strip().startswith("#") for line in resolved_lines)
        if not has_statement:
            resolved_lines.append("    pass")
        return resolved_lines, selector_map, all_resolved

    def _resolve_step(
        self, page: Page, step: FlowStep, credentials: dict | None, is_destructive_flow: bool
    ) -> tuple[str | None, str | None]:
        if step.action == "navigate":
            if not step.value:
                return None, None
            page.goto(step.value, wait_until="networkidle", timeout=15_000)
            return f"    page.goto({step.value!r})", None

        if step.action == "assert_url":
            expected = step.value or ""
            return f"    expect(page).to_have_url({expected!r})", None

        locator, selector_expr = _find_locator(page, step)
        if locator is None:
            return None, None

        if step.action == "click":
            if is_destructive_flow:
                # Safety: never actually invoke a destructive control (delete/
                # remove/cancel/deactivate), live or in the generated test —
                # confirming it resolves is as far as automation should go
                # without an explicit human-in-the-loop confirmation step.
                return (
                    f"    expect(page.{selector_expr}).to_be_visible()"
                    f"  # destructive action: click intentionally not executed, see agents/generator.py",
                    selector_expr,
                )
            locator.click(timeout=5_000)
            page.wait_for_load_state("networkidle", timeout=10_000)
            return f"    page.{selector_expr}.click()", selector_expr

        if step.action == "fill":
            live_value, code_value_expr = _resolve_value(step.value, credentials)
            locator.fill(live_value, timeout=5_000)
            return f"    page.{selector_expr}.fill({code_value_expr})", selector_expr

        if step.action == "select":
            live_value, code_value_expr = _resolve_value(step.value, credentials)
            locator.select_option(live_value, timeout=5_000)
            return f"    page.{selector_expr}.select_option({code_value_expr})", selector_expr

        if step.action == "assert_visible":
            return f"    expect(page.{selector_expr}).to_be_visible()", selector_expr

        if step.action == "assert_text":
            expected = step.value or ""
            return f"    expect(page.{selector_expr}).to_contain_text({expected!r})", selector_expr

        return None, None


def _find_locator(page: Page, step: FlowStep) -> tuple[Locator | None, str | None]:
    candidates = _candidate_descriptions(step.target_description)
    for strategy in _LOCATOR_STRATEGIES_BY_ACTION.get(step.action, ["text"]):
        for description in candidates:
            locator, expr = _build_locator(page, strategy, description)
            if locator is None:
                continue
            try:
                count = locator.count()
            except PlaywrightError:
                continue
            if count == 1:
                return locator, expr
    return None, None


# Real accessible names/labels are usually a single plain word or two ("Username",
# "Login") — the Planner's `target_description` is a fuller phrase ("Username input
# field", "Login button"). Playwright's exact=False match requires the *search
# string* to be a substring of the accessible name, so the fuller phrase alone
# never matches a short label. Stripping generic trailing words gives a second,
# much more matchable candidate.
_GENERIC_DESCRIPTOR_SUFFIXES = [
    "input field", "text field", "input box", "text box", "text area",
    "input", "field", "button", "banner", "message", "dropdown", "checkbox",
    "link", "icon", "area", "element", "control", "widget", "header", "section",
]


def _candidate_descriptions(description: str) -> list[str]:
    candidates = [description]
    current = description
    changed = True
    while changed:
        changed = False
        lowered = current.lower()
        for suffix in _GENERIC_DESCRIPTOR_SUFFIXES:
            pattern = f" {suffix}"
            if lowered.endswith(pattern) and len(current) > len(pattern):
                current = current[: -len(pattern)].strip()
                changed = True
                break
    if current and current != description:
        candidates.append(current)
    return candidates


def _build_locator(page: Page, strategy: str, description: str) -> tuple[Locator | None, str | None]:
    try:
        if strategy == "label":
            return page.get_by_label(description, exact=False), f"get_by_label({description!r})"
        if strategy == "placeholder":
            return page.get_by_placeholder(description, exact=False), f"get_by_placeholder({description!r})"
        if strategy == "role_textbox":
            expr = f"get_by_role('textbox', name={description!r})"
            return page.get_by_role("textbox", name=description, exact=False), expr
        if strategy == "role_combobox":
            expr = f"get_by_role('combobox', name={description!r})"
            return page.get_by_role("combobox", name=description, exact=False), expr
        if strategy == "role_button":
            expr = f"get_by_role('button', name={description!r})"
            return page.get_by_role("button", name=description, exact=False), expr
        if strategy == "role_link":
            expr = f"get_by_role('link', name={description!r})"
            return page.get_by_role("link", name=description, exact=False), expr
        if strategy == "text":
            return page.get_by_text(description, exact=False), f"get_by_text({description!r})"
        if strategy == "input_type_heuristic":
            return _build_input_type_locator(page, description)
    except PlaywrightError:
        return None, None
    return None, None


# Last-resort fallback for `fill` steps: some real-world forms visually place a
# label next to an input with no programmatic association at all (no `for`/
# `id`, no aria-label) — an accessibility gap in the app itself, not something
# get_by_label/role can work around, and common enough across real sites that
# it's worth a generic fallback rather than special-casing any one app. The
# HTML5 `type` attribute is usually still correct even then, since browsers
# rely on it for autofill/keyboard behavior independent of accessibility, so a
# keyword match against the description is a reasonable last resort.
_KEYWORD_TO_INPUT_TYPE = {
    "email": "email",
    "password": "password",
    "phone": "tel",
    "telephone": "tel",
    "search": "search",
    "url": "url",
}


def _build_input_type_locator(page: Page, description: str) -> tuple[Locator | None, str | None]:
    lowered = description.lower()
    for keyword, input_type in _KEYWORD_TO_INPUT_TYPE.items():
        if keyword in lowered:
            css = f'input[type="{input_type}"]'
            return page.locator(css), f"locator({css!r})"
    return None, None


def _resolve_value(value: str | None, credentials: dict | None) -> tuple[str, str]:
    """Returns (value used for this Generator's own live resolution,
    Python source expression to embed in the generated file).
    """
    if value in _PLACEHOLDER_ENV_VARS:
        env_var = _PLACEHOLDER_ENV_VARS[value]
        live_value = ""
        if credentials:
            if value == "{{username}}":
                live_value = credentials.get("username") or credentials.get("email") or ""
            elif value == "{{password}}":
                live_value = credentials.get("password") or ""
        return live_value, f"os.environ[{env_var!r}]"
    return value or "", repr(value or "")


def _ensure_conftest() -> None:
    conftest_path = GENERATED_TESTS_DIR / "conftest.py"
    conftest_path.write_text(_CONFTEST_CONTENT, encoding="utf-8")


def _write_resolved_test_file(file_path: Path, flow: Flow, resolved_lines: list[str]) -> None:
    needs_os = any("os.environ" in line for line in resolved_lines)
    header = [
        '"""Auto-generated by Generator: steps resolved against the live application."""',
        *(["import os"] if needs_os else []),
        "from playwright.sync_api import expect",
        "",
        f"def test_{flow.flow_id.replace('-', '_')}(page):",
        f"    # Flow: {flow.title} (category={flow.category}, priority={flow.priority})",
    ]
    content = "\n".join(header + resolved_lines) + "\n"
    file_path.write_text(content, encoding="utf-8")


def _write_fallback_test_file(file_path: Path, flow: Flow, target_url: str | None) -> None:
    header = [
        '"""Auto-generated by Generator (live resolution failed — placeholder smoke test)."""',
        "import pytest",
        "",
        f"def test_{flow.flow_id.replace('-', '_')}(page):",
        f"    # Flow: {flow.title} (category={flow.category}, priority={flow.priority})",
    ]
    step_comments = [
        f"    # TODO step {step.step_id}: {step.action} -> {step.target_description!r}" for step in flow.steps
    ]
    if target_url:
        body = [
            f"    page.goto({target_url!r})",
            "    assert page.title() is not None  # TODO: replace with resolved per-step assertions",
        ]
    else:
        body = ["    pytest.skip('TODO: no navigable target_description resolved for this flow yet')"]

    content = "\n".join(header + step_comments + body) + "\n"
    file_path.write_text(content, encoding="utf-8")
